### ISSUE TITLE
tap-adwords does not currently support the 'SHOPPING_PERFORMANCE_REPORT'

### ISSUE THREAD

**Issue by dylan-stitch** [singer-io/tap-adwords#20]
"The Shopping Performance report provides shopping campaign statistics aggregated at the product (OfferId field) level. Product dimension values from Merchant Center such as brand, category, custom attributes, product condition and product type will reflect the state of each dimension as of the date and time when AdWords recorded the corresponding event."

This report is currently unavailable through tap-adwords, and is commented out:
https://github.com/singer-io/tap-adwords/blob/master/tap_adwords/__init__.py#L102

Google's docs for the report can be found here:
https://developers.google.com/adwords/api/docs/appendix/reports/shopping-performance-report

**Comment by dmosorast** [comment]
Merged from #25 and released in version 1.4.0
