### ISSUE TITLE
selected property is missing from catalog produced from discover

### ISSUE THREAD

**Issue by Jagjit-Thind** [singer-io/tap-adwords#68]
The catalog produced by running `--discover` function is missing the `selected` property, called from`tap-adwords --config config.json --discover > catalog.json` , see example below.

Stream is skipped when running tap if the `selected` property is not `true`
```
{
    "stream": "campaigns",
    "tap_stream_id": "campaigns",
    "schema": {
    ...
    },
    "metadata": [
      {
        "metadata": {
          "inclusion": "available",
        },
        "breadcrumb": []
      }
    ]
}
```

**Comment by hz-lschick** [comment]
@Jagjit-Thind This is the default behavior of many singer taps. You have to modify the catalog file after discovery and add the 'selected' property yourself.

**Comment by hz-lschick** [comment]
here a cli tool you can use to modify the catalog file: [singer-discover](https://github.com/chrisgoddard/singer-discover)
